### ISSUE TITLE
Capital letter in prompt [yes/no] means default value

### ISSUE THREAD

**Issue by snebjorn** [dotnet/cli-lab#135] opened 2020-03-31 07:48 UTC
Hi I just noticed this when running the tool

> Do you want to continue? [Y/n]
> Allowed values are "Y", "YES", and "N".

Usually `[Y/n]` means that the capital letter is the default should you just press enter.

**Comment by sfoslund** [comment] 2020-03-31 17:35
Thanks for the feedback. It looks like this is a duplicate of #119, so I'm closing this one in favor of that

**Closed by sfoslund** 2020-03-31 17:35 UTC
