### ISSUE TITLE
.NET Core Uninstall Tool doesn't appear to be working on MacOS (Catalina)

### ISSUE THREAD

**Issue by cmjchrisjones** [dotnet/cli-lab#115] opened 2020-01-30 03:26 UTC
I've come across two errors since trying to use this tool on a Mac...

The version used is the one currently available on GitHub [here](https://github.com/dotnet/cli-lab/releases) - 0.1.0-preview.19524.4 Pre-release

1: The `--version` command isn't working, as its expecting another command:
![image](https://user-images.githubusercontent.com/3969086/73416941-4f76a480-430e-11ea-8029-1ece052dada2.png)

![image](https://user-images.githubusercontent.com/3969086/73416835-09214580-430e-11ea-9eaf-87580de1d062.png)

2: When doing a dry-run or trying to remove an SDK or runtime, a stacktrace is returned.

|What?|Info|Screenshot|
|:-:|:-:|:-:|
|MacOS|10.15.3 Beta (19D49f) Catalina|![image](https://user-images.githubusercontent.com/3969086/73415935-37e9ec80-430b-11ea-83f0-a15f180379d4.png)|
| Listing Runtimes & SDKS |  |![image](https://user-images.githubusercontent.com/3969086/73417014-88af1480-430e-11ea-9eb3-e8fe1b38c563.png)|
| Trying to remove a SDK | command run: `./dotnet-core-uninstall remove 2.1.4 --sdk` | ![image](https://user-images.githubusercontent.com/3969086/73417424-eb54e000-430f-11ea-972c-4be8e2bdee1d.png)| 

## Error thrown removing the SDK

```Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Collections.Generic.ComparisonComparer`1[System.Int32]'.
   at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(Object comparer)
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.DotNet.Tools.Uninstall.Shared.VSVersioning.VisualStudioSafeVersionsExtractor.GetReasonRequiredStrings(IEnumerable`1 allBundles)
   at Microsoft.DotNet.Tools.Uninstall.Shared.Commands.CommandBundleFilter.GetFilteredWithRequirementStrings()
   at Microsoft.DotNet.Tools.Uninstall.Shared.Commands.UninstallCommandExec.Execute()
   at Microsoft.DotNet.Tools.Uninstall.Shared.Configs.CommandLineConfigs.<>c.<.cctor>b__39_6()
   at Microsoft.DotNet.Tools.Uninstall.Shared.Exceptions.ExceptionHandler.<>c__DisplayClass0_0.<HandleException>b__0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass2_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext()```

A similar/identical issue is also thrown when attempting the same for runtimes or dry runs

**Comment by Juandi-M** [comment] 2020-01-30 16:37
Same here

**Comment by sfoslund** [comment] 2020-01-30 19:45
Thanks for filing this issue! It looks like issue 1 is a duplicate of #105 and issue 2 is a duplicate of #112, both of which have been fixed.

**Closed by sfoslund** 2020-01-30 19:45 UTC

**Comment by sfoslund** [comment] 2020-02-10 18:23
This issue has been resolved with the latest prerelease, try it out [here](https://github.com/dotnet/cli-lab/releases/tag/0.1.0-preview.20073.1).
